### ISSUE TITLE
Status menu applications: odd behavior on multiple displays

### ISSUE THREAD

**Issue by jhcsu** [sveinbjornt/Platypus#53]
I have noticed an intermittent problem with Status Menu applications that run in the background.  The problem only pops up when I have multiple displays, and I click on a Status Menu application which is running on a menu bar on the inactive display (i.e., the menu bar is partially transparent).  I am running OS X 10.10.4.

It is perhaps best described with an example:
- On my main display (the one with the Dock) I click my app, DemoApp, in the menu bar.  It displays "Choice A", "Choice B", and "Quit DemoApp" as expected.
- I go to my secondary display and open a window, do some work, etc.
- I bring the mouse back to the main display and click on DemoApp (note at this point, the menu bar is partially transparent, as it is active on the secondary display and not this one).  It displays only "Quit DemoApp".  The choices are not displayed.  Uh oh.
- The second time I click DemoApp, the normal behavior returns.
- I can now _sometimes_ repeat this example from the top. It doesn't seem to happen every time.

Thanks, let me know if that doesn't make sense or you'd like a screen capture of the problem.

**Comment by jhcsu** [comment]
Update: I've noticed this error periodically when using a single display, and if may have nothing to do with multiple displays.

I can't come up with a procedure to produce the problem every time.  However if I just sit here and slowly and continually click my Status Menu application in the menu bar, about 1 in 25 times or so it will come up with "Quit ..." as the only selection.

**Comment by sveinbjornt** [comment]
This is now fixed in master.

**Comment by jhcsu** [comment]
I'm still seeing this occasionally in 5.0... it's hard to repeat, but maybe 1 in every 30 times I click the app in the menu bar, all that's there is "Quit ...".  Click elsewhere, then go back, and everything is fine.

**Comment by sveinbjornt** [comment]
Hmmm.... I'll take a closer look.

**Comment by jhcsu** [comment]
Here's some more information that might help.  I've figured out a way to reproduce the problem in a pretty robust way, at least on my system.  This method requires multiple monitors.

1. Click the Status Menu app on screen 1.
2. Click the desktop of screen 1.
3. Click the Status Menu app on screen 2.
(Maybe 1 out of 2 times this produces an "empty" menu.  If not, continue.)
4. Click the desktop of screen 2.
5. Click the Status Menu app on screen 1.
(Maybe 4 out out of 5 times this produces an "empty" menu.  If not, start again from step 2.  If I keep playing this back and forth game, the error always pops up within a few seconds!

This is just a way to demonstrate a problem that otherwise seems to pop up "randomly".

**Comment by sveinbjornt** [comment]
Now fixed in master.
